services:
  mongo:
    image: mongo:6
    container_name: gracie-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo:/data/db
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gracie-api
    depends_on:
      - mongo
    environment:
      PORT: 8080
      ENC_KEY_FILE: /app/secrets/enc.key
      DATA_STORE: mongo
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: gracie
    ports:
      - "8080:8080"
    volumes:
      - ./.secrets:/app/secrets
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Override as needed
        VITE_LIVE_QUERY_LISTS_MS: 4000
        VITE_LIVE_QUERY_ITEMS_MS: 2000
    container_name: gracie-frontend
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: unless-stopped

  # Optional: frontend dev server (uncomment to use)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: gracie-frontend
  #   environment:
  #     VITE_API_BASE_URL: http://localhost:8080
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - api
    
