package categorization

// Anchor maps a lowercase keyword/phrase to a category label. It carries no
// domain assumptions — the same type is reused for any categorization domain.
// The ordering of an anchor set matters for substring matching (specific
// phrases first), and the same set doubles as the anchor set for embedding kNN.
type Anchor struct {
	Term     string
	Category string
}

// GroceryAnchors is the grocery domain's anchor set — the single source of
// truth for both keyword matching and embedding anchors. Add new items here
// (data, not logic). Other domains define their own sets (e.g. ListTypeAnchors).
var GroceryAnchors = []Anchor{
	// Specific Exceptions (Highest Priority to avoid substring collisions)
	{Term: "butternut squash", Category: "Produce"},
	{Term: "winter squash", Category: "Produce"},
	{Term: "banana ketchup", Category: "Pantry"},
	{Term: "peanut butter", Category: "Pantry"},
	{Term: "almond butter", Category: "Pantry"},
	{Term: "milkfish", Category: "Meat & Seafood"},
	{Term: "tenderstem broccoli", Category: "Produce"},
	{Term: "dinorado rice", Category: "Grains & Bakery"},
	{Term: "arborio rice", Category: "Grains & Bakery"},
	{Term: "canellini beans", Category: "Pantry"},
	{Term: "purefoods hotdog", Category: "Meat & Seafood"},
	{Term: "san marzano", Category: "Produce"},
	{Term: "balsamic vinegar", Category: "Pantry"},
	{Term: "truffle oil", Category: "Pantry"},
	{Term: "extra virgin olive oil", Category: "Pantry"},
	{Term: "pancit bihon", Category: "Grains & Bakery"},
	{Term: "sinigang mix", Category: "Pantry"},
	{Term: "mang tomas", Category: "Pantry"},
	{Term: "ube halaya", Category: "Pantry"},
	{Term: "blue cheese", Category: "Eggs & Dairy"},
	{Term: "goat cheese", Category: "Eggs & Dairy"},
	{Term: "grana padano", Category: "Eggs & Dairy"},
	{Term: "eden cheese", Category: "Eggs & Dairy"},

	// Household & Personal (Moved up to avoid "ham" in "shampoo", etc.)
	{Term: "shaving cream", Category: "Household"},
	{Term: "shaving", Category: "Household"},
	{Term: "toilet paper", Category: "Household"},
	{Term: "kitchen roll", Category: "Household"},
	{Term: "paper towel", Category: "Household"},
	{Term: "trash bag", Category: "Household"},
	{Term: "garbage bag", Category: "Household"},
	{Term: "bin bag", Category: "Household"},
	{Term: "soap", Category: "Household"},
	{Term: "hand wash", Category: "Household"},
	{Term: "shower gel", Category: "Household"},
	{Term: "shampoo", Category: "Household"},
	{Term: "conditioner", Category: "Household"},
	{Term: "toothpaste", Category: "Household"},
	{Term: "toothbrush", Category: "Household"},
	{Term: "floss", Category: "Household"},
	{Term: "mouthwash", Category: "Household"},
	{Term: "deodorant", Category: "Household"},
	{Term: "razor", Category: "Household"},
	{Term: "laundry detergent", Category: "Household"},
	{Term: "fabric softener", Category: "Household"},
	{Term: "dish soap", Category: "Household"},
	{Term: "dishwasher tablets", Category: "Household"},
	{Term: "cleaning spray", Category: "Household"},
	{Term: "bleach", Category: "Household"},
	{Term: "sponge", Category: "Household"},
	{Term: "scrubber", Category: "Household"},
	{Term: "tissues", Category: "Household"},
	{Term: "napkins", Category: "Household"},
	{Term: "foil", Category: "Household"},
	{Term: "cling film", Category: "Household"},
	{Term: "plastic wrap", Category: "Household"},
	{Term: "baking paper", Category: "Household"},
	{Term: "parchment paper", Category: "Household"},
	{Term: "cleaner", Category: "Household"},
	{Term: "paste", Category: "Household"},

	// Meat & Seafood
	{Term: "bangus", Category: "Meat & Seafood"},
	{Term: "tilapia", Category: "Meat & Seafood"},
	{Term: "galunggong", Category: "Meat & Seafood"},
	{Term: "danggit", Category: "Meat & Seafood"},
	{Term: "tuyo", Category: "Meat & Seafood"},
	{Term: "longganisa", Category: "Meat & Seafood"},
	{Term: "tocino", Category: "Meat & Seafood"},
	{Term: "prosciutto", Category: "Meat & Seafood"},
	{Term: "guanciale", Category: "Meat & Seafood"},
	{Term: "mortadella", Category: "Meat & Seafood"},
	{Term: "salami", Category: "Meat & Seafood"},
	{Term: "pepperoni", Category: "Meat & Seafood"},
	{Term: "hotdog", Category: "Meat & Seafood"},
	{Term: "sausage", Category: "Meat & Seafood"},
	{Term: "corned beef", Category: "Meat & Seafood"},
	{Term: "spam", Category: "Meat & Seafood"},
	{Term: "chicken breast", Category: "Meat & Seafood"},
	{Term: "chicken thigh", Category: "Meat & Seafood"},
	{Term: "minced beef", Category: "Meat & Seafood"},
	{Term: "ground beef", Category: "Meat & Seafood"},
	{Term: "steak", Category: "Meat & Seafood"},
	{Term: "beef", Category: "Meat & Seafood"},
	{Term: "pork", Category: "Meat & Seafood"},
	{Term: "bacon", Category: "Meat & Seafood"},
	{Term: "ham", Category: "Meat & Seafood"},
	{Term: "turkey", Category: "Meat & Seafood"},
	{Term: "lamb", Category: "Meat & Seafood"},
	{Term: "duck", Category: "Meat & Seafood"},
	{Term: "venison", Category: "Meat & Seafood"},
	{Term: "meatball", Category: "Meat & Seafood"},
	{Term: "burger", Category: "Meat & Seafood"},
	{Term: "salmon", Category: "Meat & Seafood"},
	{Term: "cod", Category: "Meat & Seafood"},
	{Term: "haddock", Category: "Meat & Seafood"},
	{Term: "sea bass", Category: "Meat & Seafood"},
	{Term: "trout", Category: "Meat & Seafood"},
	{Term: "shrimp", Category: "Meat & Seafood"},
	{Term: "prawn", Category: "Meat & Seafood"},
	{Term: "crab", Category: "Meat & Seafood"},
	{Term: "lobster", Category: "Meat & Seafood"},
	{Term: "mussels", Category: "Meat & Seafood"},
	{Term: "clams", Category: "Meat & Seafood"},
	{Term: "scallops", Category: "Meat & Seafood"},
	{Term: "tuna steak", Category: "Meat & Seafood"},
	{Term: "fish", Category: "Meat & Seafood"},
	{Term: "meat", Category: "Meat & Seafood"},

	// Grains, Pasta & Bakery
	{Term: "piadina", Category: "Grains & Bakery"},
	{Term: "focaccia", Category: "Grains & Bakery"},
	{Term: "panettone", Category: "Grains & Bakery"},
	{Term: "pandesal", Category: "Grains & Bakery"},
	{Term: "pan de coco", Category: "Grains & Bakery"},
	{Term: "gnocchi", Category: "Grains & Bakery"},
	{Term: "pasta", Category: "Grains & Bakery"},
	{Term: "noodle", Category: "Grains & Bakery"},
	{Term: "rice", Category: "Grains & Bakery"},
	{Term: "quinoa", Category: "Grains & Bakery"},
	{Term: "spaghetti", Category: "Grains & Bakery"},
	{Term: "penne", Category: "Grains & Bakery"},
	{Term: "fusilli", Category: "Grains & Bakery"},
	{Term: "tagliatelle", Category: "Grains & Bakery"},
	{Term: "linguine", Category: "Grains & Bakery"},
	{Term: "fettuccine", Category: "Grains & Bakery"},
	{Term: "lasagna", Category: "Grains & Bakery"},
	{Term: "lasagne", Category: "Grains & Bakery"},
	{Term: "tortellini", Category: "Grains & Bakery"},
	{Term: "ravioli", Category: "Grains & Bakery"},
	{Term: "couscous", Category: "Grains & Bakery"},
	{Term: "bulgur", Category: "Grains & Bakery"},
	{Term: "oat", Category: "Grains & Bakery"},
	{Term: "porridge", Category: "Grains & Bakery"},
	{Term: "flour", Category: "Grains & Bakery"},
	{Term: "bread", Category: "Grains & Bakery"},
	{Term: "sourdough", Category: "Grains & Bakery"},
	{Term: "baguette", Category: "Grains & Bakery"},
	{Term: "ciabatta", Category: "Grains & Bakery"},
	{Term: "bagel", Category: "Grains & Bakery"},
	{Term: "tortilla", Category: "Grains & Bakery"},
	{Term: "pita", Category: "Grains & Bakery"},
	{Term: "naan", Category: "Grains & Bakery"},
	{Term: "croissant", Category: "Grains & Bakery"},
	{Term: "muffin", Category: "Grains & Bakery"},
	{Term: "crumpet", Category: "Grains & Bakery"},
	{Term: "cereal", Category: "Grains & Bakery"},
	{Term: "granola", Category: "Grains & Bakery"},
	{Term: "muesli", Category: "Grains & Bakery"},

	// Produce (Vegetables & Herbs)
	{Term: "calamansi", Category: "Produce"},
	{Term: "artichoke", Category: "Produce"},
	{Term: "okra", Category: "Produce"},
	{Term: "pak choi", Category: "Produce"},
	{Term: "bok choi", Category: "Produce"},
	{Term: "mange tout", Category: "Produce"},
	{Term: "sugar snap", Category: "Produce"},
	{Term: "baby corn", Category: "Produce"},
	{Term: "coriander", Category: "Produce"},
	{Term: "cilantro", Category: "Produce"},
	{Term: "parsley", Category: "Produce"},
	{Term: "basil", Category: "Produce"},
	{Term: "mint", Category: "Produce"},
	{Term: "rosemary", Category: "Produce"},
	{Term: "thyme", Category: "Produce"},
	{Term: "chives", Category: "Produce"},
	{Term: "dill", Category: "Produce"},
	{Term: "sage", Category: "Produce"},
	{Term: "oregano", Category: "Produce"},
	{Term: "tarragon", Category: "Produce"},
	{Term: "lemongrass", Category: "Produce"},
	{Term: "ginger", Category: "Produce"},
	{Term: "turmeric", Category: "Produce"},
	{Term: "chili", Category: "Produce"},
	{Term: "chilli", Category: "Produce"},
	{Term: "jalapeno", Category: "Produce"},
	{Term: "sweet potato", Category: "Produce"},
	{Term: "bell pepper", Category: "Produce"},
	{Term: "broccoli", Category: "Produce"},
	{Term: "carrot", Category: "Produce"},
	{Term: "onion", Category: "Produce"},
	{Term: "scallion", Category: "Produce"},
	{Term: "spring onion", Category: "Produce"},
	{Term: "garlic", Category: "Produce"},
	{Term: "kale", Category: "Produce"},
	{Term: "spinach", Category: "Produce"},
	{Term: "lettuce", Category: "Produce"},
	{Term: "arugula", Category: "Produce"},
	{Term: "rocket", Category: "Produce"},
	{Term: "cucumber", Category: "Produce"},
	{Term: "tomato", Category: "Produce"},
	{Term: "pepper", Category: "Produce"},
	{Term: "potato", Category: "Produce"},
	{Term: "mushroom", Category: "Produce"},
	{Term: "zucchini", Category: "Produce"},
	{Term: "courgette", Category: "Produce"},
	{Term: "asparagus", Category: "Produce"},
	{Term: "cabbage", Category: "Produce"},
	{Term: "cauliflower", Category: "Produce"},
	{Term: "celery", Category: "Produce"},
	{Term: "eggplant", Category: "Produce"},
	{Term: "aubergine", Category: "Produce"},
	{Term: "leek", Category: "Produce"},
	{Term: "radish", Category: "Produce"},
	{Term: "pea", Category: "Produce"},
	{Term: "bean", Category: "Produce"},
	{Term: "corn on the cob", Category: "Produce"},
	{Term: "sweetcorn", Category: "Produce"},

	// Produce (Fruits)
	{Term: "pomegranate", Category: "Produce"},
	{Term: "dragon fruit", Category: "Produce"},
	{Term: "passion fruit", Category: "Produce"},
	{Term: "pineapple", Category: "Produce"},
	{Term: "coconut", Category: "Produce"},
	{Term: "strawberry", Category: "Produce"},
	{Term: "blueberry", Category: "Produce"},
	{Term: "raspberry", Category: "Produce"},
	{Term: "blackberry", Category: "Produce"},
	{Term: "cranberry", Category: "Produce"},
	{Term: "cherry", Category: "Produce"},
	{Term: "apricot", Category: "Produce"},
	{Term: "nectarine", Category: "Produce"},
	{Term: "peach", Category: "Produce"},
	{Term: "plum", Category: "Produce"},
	{Term: "fig", Category: "Produce"},
	{Term: "date", Category: "Produce"},
	{Term: "papaya", Category: "Produce"},
	{Term: "guava", Category: "Produce"},
	{Term: "lychee", Category: "Produce"},
	{Term: "mango", Category: "Produce"},
	{Term: "kiwi", Category: "Produce"},
	{Term: "melon", Category: "Produce"},
	{Term: "watermelon", Category: "Produce"},
	{Term: "cantaloupe", Category: "Produce"},
	{Term: "honeydew", Category: "Produce"},
	{Term: "pear", Category: "Produce"},
	{Term: "apple", Category: "Produce"},
	{Term: "banana", Category: "Produce"},
	{Term: "lemon", Category: "Produce"},
	{Term: "lime", Category: "Produce"},
	{Term: "grapefruit", Category: "Produce"},
	{Term: "orange", Category: "Produce"},
	{Term: "tangerine", Category: "Produce"},
	{Term: "clementine", Category: "Produce"},
	{Term: "satsuma", Category: "Produce"},
	{Term: "mandarin", Category: "Produce"},
	{Term: "grape", Category: "Produce"},
	{Term: "berry", Category: "Produce"},
	{Term: "avocado", Category: "Produce"},

	// Eggs & Dairy & Alternatives
	{Term: "parmigiano", Category: "Eggs & Dairy"},
	{Term: "pecorino", Category: "Eggs & Dairy"},
	{Term: "burrata", Category: "Eggs & Dairy"},
	{Term: "mozzarella", Category: "Eggs & Dairy"},
	{Term: "ricotta", Category: "Eggs & Dairy"},
	{Term: "mascarpone", Category: "Eggs & Dairy"},
	{Term: "feta", Category: "Eggs & Dairy"},
	{Term: "halloumi", Category: "Eggs & Dairy"},
	{Term: "cheddar", Category: "Eggs & Dairy"},
	{Term: "parmesan", Category: "Eggs & Dairy"},
	{Term: "oat milk", Category: "Eggs & Dairy"},
	{Term: "almond milk", Category: "Eggs & Dairy"},
	{Term: "soy milk", Category: "Eggs & Dairy"},
	{Term: "coconut milk", Category: "Eggs & Dairy"},
	{Term: "sour cream", Category: "Eggs & Dairy"},
	{Term: "heavy cream", Category: "Eggs & Dairy"},
	{Term: "whipping cream", Category: "Eggs & Dairy"},
	{Term: "double cream", Category: "Eggs & Dairy"},
	{Term: "creme fraiche", Category: "Eggs & Dairy"},
	{Term: "cottage cheese", Category: "Eggs & Dairy"},
	{Term: "cream cheese", Category: "Eggs & Dairy"},
	{Term: "milk", Category: "Eggs & Dairy"},
	{Term: "cheese", Category: "Eggs & Dairy"},
	{Term: "butter", Category: "Eggs & Dairy"},
	{Term: "margarine", Category: "Eggs & Dairy"},
	{Term: "yogurt", Category: "Eggs & Dairy"},
	{Term: "jogurt", Category: "Eggs & Dairy"},
	{Term: "kefir", Category: "Eggs & Dairy"},
	{Term: "cream", Category: "Eggs & Dairy"},
	{Term: "curd", Category: "Eggs & Dairy"},
	{Term: "egg", Category: "Eggs & Dairy"},

	// Frozen
	{Term: "frozen pizza", Category: "Frozen"},
	{Term: "ice cream", Category: "Frozen"},
	{Term: "sorbet", Category: "Frozen"},
	{Term: "gelato", Category: "Frozen"},
	{Term: "frozen peas", Category: "Frozen"},
	{Term: "frozen berries", Category: "Frozen"},
	{Term: "frozen fruit", Category: "Frozen"},
	{Term: "frozen veg", Category: "Frozen"},
	{Term: "frozen corn", Category: "Frozen"},
	{Term: "chicken nugget", Category: "Frozen"},
	{Term: "fish finger", Category: "Frozen"},
	{Term: "fish stick", Category: "Frozen"},
	{Term: "tater tot", Category: "Frozen"},
	{Term: "hash brown", Category: "Frozen"},
	{Term: "waffle", Category: "Frozen"},
	{Term: "frozen", Category: "Frozen"},

	// Plant-Based Protein
	{Term: "plant-based", Category: "Plant-Based"},
	{Term: "meat-free", Category: "Plant-Based"},
	{Term: "tofu", Category: "Plant-Based"},
	{Term: "tempeh", Category: "Plant-Based"},
	{Term: "seitan", Category: "Plant-Based"},
	{Term: "vegan", Category: "Plant-Based"},
	{Term: "beyond meat", Category: "Plant-Based"},
	{Term: "impossible burger", Category: "Plant-Based"},
	{Term: "nutritional yeast", Category: "Plant-Based"},
	{Term: "quorn", Category: "Plant-Based"},
	{Term: "hummus", Category: "Plant-Based"},
	{Term: "falafel", Category: "Plant-Based"},

	// Pantry & Spices
	{Term: "kimchi", Category: "Pantry"},
	{Term: "lupini", Category: "Pantry"},
	{Term: "pesto", Category: "Pantry"},
	{Term: "bagoong", Category: "Pantry"},
	{Term: "patis", Category: "Pantry"},
	{Term: "black pepper", Category: "Pantry"},
	{Term: "white pepper", Category: "Pantry"},
	{Term: "cayenne", Category: "Pantry"},
	{Term: "paprika", Category: "Pantry"},
	{Term: "cinnamon", Category: "Pantry"},
	{Term: "cumin", Category: "Pantry"},
	{Term: "coriander seeds", Category: "Pantry"},
	{Term: "turmeric powder", Category: "Pantry"},
	{Term: "maple syrup", Category: "Pantry"},
	{Term: "honey", Category: "Pantry"},
	{Term: "agave", Category: "Pantry"},
	{Term: "soy sauce", Category: "Pantry"},
	{Term: "tamari", Category: "Pantry"},
	{Term: "fish sauce", Category: "Pantry"},
	{Term: "olive oil", Category: "Pantry"},
	{Term: "canola oil", Category: "Pantry"},
	{Term: "vegetable oil", Category: "Pantry"},
	{Term: "coconut oil", Category: "Pantry"},
	{Term: "sesame oil", Category: "Pantry"},
	{Term: "vinegar", Category: "Pantry"},
	{Term: "balsamic", Category: "Pantry"},
	{Term: "ketchup", Category: "Pantry"},
	{Term: "mayo", Category: "Pantry"},
	{Term: "mustard", Category: "Pantry"},
	{Term: "hot sauce", Category: "Pantry"},
	{Term: "sriracha", Category: "Pantry"},
	{Term: "pasta sauce", Category: "Pantry"},
	{Term: "tomato paste", Category: "Pantry"},
	{Term: "canned tomato", Category: "Pantry"},
	{Term: "tinned tomato", Category: "Pantry"},
	{Term: "baked beans", Category: "Pantry"},
	{Term: "chickpeas", Category: "Pantry"},
	{Term: "lentils", Category: "Pantry"},
	{Term: "kidney beans", Category: "Pantry"},
	{Term: "tuna", Category: "Pantry"},
	{Term: "sardines", Category: "Pantry"},
	{Term: "soup", Category: "Pantry"},
	{Term: "stock cube", Category: "Pantry"},
	{Term: "bouillon", Category: "Pantry"},
	{Term: "salt", Category: "Pantry"},
	{Term: "sugar", Category: "Pantry"},
	{Term: "brown sugar", Category: "Pantry"},
	{Term: "icing sugar", Category: "Pantry"},
	{Term: "baking powder", Category: "Pantry"},
	{Term: "baking soda", Category: "Pantry"},
	{Term: "yeast", Category: "Pantry"},
	{Term: "nutella", Category: "Pantry"},
	{Term: "jam", Category: "Pantry"},
	{Term: "marmalade", Category: "Pantry"},
	{Term: "oil", Category: "Pantry"},
	{Term: "spice", Category: "Pantry"},
	{Term: "sauce", Category: "Pantry"},
	{Term: "syrup", Category: "Pantry"},
	{Term: "nut", Category: "Pantry"},
	{Term: "walnut", Category: "Pantry"},
	{Term: "almond", Category: "Pantry"},
	{Term: "cashew", Category: "Pantry"},
	{Term: "peanut", Category: "Pantry"},
	{Term: "seed", Category: "Pantry"},
	{Term: "chia", Category: "Pantry"},
	{Term: "pumpkin seed", Category: "Pantry"},
	{Term: "sunflower seed", Category: "Pantry"},
	{Term: "chips", Category: "Pantry"},
	{Term: "crisps", Category: "Pantry"},
	{Term: "popcorn", Category: "Pantry"},
	{Term: "pretzels", Category: "Pantry"},
	{Term: "crackers", Category: "Pantry"},
	{Term: "biscuits", Category: "Pantry"},
	{Term: "cookies", Category: "Pantry"},
	{Term: "chocolate", Category: "Pantry"},
	{Term: "candy", Category: "Pantry"},
	{Term: "sweets", Category: "Pantry"},

	// Beverages
	{Term: "coffee beans", Category: "Beverages"},
	{Term: "ground coffee", Category: "Beverages"},
	{Term: "instant coffee", Category: "Beverages"},
	{Term: "tea bags", Category: "Beverages"},
	{Term: "green tea", Category: "Beverages"},
	{Term: "herbal tea", Category: "Beverages"},
	{Term: "orange juice", Category: "Beverages"},
	{Term: "apple juice", Category: "Beverages"},
	{Term: "juice", Category: "Beverages"},
	{Term: "soda", Category: "Beverages"},
	{Term: "pop", Category: "Beverages"},
	{Term: "coke", Category: "Beverages"},
	{Term: "pepsi", Category: "Beverages"},
	{Term: "lemonade", Category: "Beverages"},
	{Term: "sparkling water", Category: "Beverages"},
	{Term: "tonic water", Category: "Beverages"},
	{Term: "mineral water", Category: "Beverages"},
	{Term: "energy drink", Category: "Beverages"},
	{Term: "kombucha", Category: "Beverages"},
	{Term: "smoothie", Category: "Beverages"},
	{Term: "wine", Category: "Beverages"},
	{Term: "beer", Category: "Beverages"},
	{Term: "ale", Category: "Beverages"},
	{Term: "lager", Category: "Beverages"},
	{Term: "cider", Category: "Beverages"},
	{Term: "spirits", Category: "Beverages"},
	{Term: "vodka", Category: "Beverages"},
	{Term: "gin", Category: "Beverages"},
	{Term: "whisky", Category: "Beverages"},
	{Term: "rum", Category: "Beverages"},
	{Term: "water", Category: "Beverages"},
	{Term: "coffee", Category: "Beverages"},
	{Term: "tea", Category: "Beverages"},
	{Term: "drink", Category: "Beverages"},
}
