name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    name: Backend (Go)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Run unit tests
        working-directory: backend
        run: go test ./... -count=1 -cover

  frontend:
    name: Frontend (Vitest)
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Verify pnpm
        run: pnpm -v
      - name: Install deps
        working-directory: frontend
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        working-directory: frontend
        run: pnpm test:ci
